# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Julia Nguyen
email: ux@jvlia.co
description: > # this means to ignore newlines until "baseurl:"
  This is a digital resume for Julia Nguyen built with [Jekyll](http://www.jekyllrb.com) and stylized with [Bootstrap](http://getbootstrap.com).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://github_username.github.com" # the base hostname & protocol for your site
twitter_username: uxjulia
github_username:  uxjulia
# Build settings
markdown: kramdown
keep: ["assets"]